[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [[redirects]]
  from = "drive/*"
  to = "/index.html"
  status = 200
  [[redirects]]
  from = "/*"
  to = "/pages/index.js"
  status = 200
