[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[redirects]]
  from = "/drive"
  to = "/drive/xx.js"
  status = 200
  force = true # COMMENT: ensure that we always redirect
